routes/web.php
<?php

use App\Http\Controllers\ExpenseController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware(['auth'])->group( function () {

    Route::get('/', function () {
        return view('dashboard');
    });

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::patch('expenses/{expense}/status', [ExpenseController::class, 'changeStatus']);
    Route::resource('expenses', ExpenseController::class);
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/expenses/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expenses') }}
        </h2>
    </x-slot>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <br />
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('expenses.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 jumbotron">
        
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('expenses.store') }}" method="POST"  enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Name*:</strong>
                            <input type="text" name="name" class="form-control" placeholder="Name" value="{{old('name')}}">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Date*:</strong>
                            <input type="text" name="date" class="form-control" placeholder="EX: {{date('Y-m-d')}}" value="{{old('date')}}">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Amount*:</strong>
                            <input type="number" name="amount" class="form-control" placeholder="EX: 200.00" value="{{old('amount')}}">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Attach*:</strong>(jpeg,png,jpg,gif,svg,pdf)
                            <div class="custom-file">
                                <input type="file" name="attach" class="form-control" id="chooseFile">
                                <!-- <label class="custom-file-label" for="chooseFile">Select file</label> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</x-app-layout>

resources/views/expenses/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expenses') }}
        </h2>
    </x-slot>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('expenses.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 jumbotron">

            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif

            <form action="{{ route('expenses.update', $expense->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Name:</strong>
                            <input type="text" name="name" value="{{ $expense->name }}" class="form-control" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Date:</strong>
                            <input type="text" name="date" class="form-control" placeholder="{{ $expense->date }}"
                                value="{{ $expense->date }}">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Amount:</strong>
                            <input type="number" name="amount" class="form-control" placeholder="{{ $expense->amount }}"
                                value="{{ $expense->amount }}">
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Attach:</strong>(jpeg,png,jpg,gif,svg,pdf)
                            <div class="custom-file">
                                <input type="file" name="attach" class="form-control" id="chooseFile">
                                <!-- <label class="custom-file-label" for="chooseFile">Select file</label> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</x-app-layout>

resources/views/expenses/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expenses') }}
        </h2>
    </x-slot>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <br />
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('expenses.create') }}" title="Create a expense"> <i class="fas fa-plus-circle"></i>
                    </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Attach</th>
            <th>Status</th>
            <th>Date Created</th>
            <th width="280px">Action</th>
        </tr>
        @if($expenses->count() == 0)
            <tr> <td colspan="8">Add first Expense for you</td> </tr>
        @endif

        @foreach ($expenses as $expense)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $expense->name }}</td>
                <td>{{ $expense->date }}</td>
                <td>{{ $expense->amount }}</td>
                <td><a href="{{ $expense->attach }}" target="_blank" download>Download</a></td>
                <td class="text-center uppercase">
                    <span data-id="{{ $expense->id }}" class="@if($expense->isPending()) btn btn-link btn-modal-change-status @endif status-color-{{ $expense->status }} "
                    >
                        {{ $expense->status }}
                    </span>
                </td>
                <td>{{ date_format($expense->created_at, 'Y-m-d') }}</td>
                <td>
                    <form action="{{ route('expenses.destroy', $expense->id) }}" method="POST">

                        <a href="{{ route('expenses.show', $expense->id) }}" title="show">
                            <i class="fas fa-eye text-success  fa-lg"></i>
                        </a>&nbsp;

                        <a href="{{ route('expenses.edit', $expense->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>
                        </a>&nbsp;

                        @csrf
                        @method('DELETE')
                        <button type="submit" title="delete" style="border: none; background-color:transparent;">
                            <i class="fas fa-trash fa-lg text-danger"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    {!! $expenses->links() !!}

    @include('expenses.modal-change-status')

</x-app-layout>

resources/views/expenses/modal-change-status.blade.php
<!-- The Modal -->
<div class="modal" id="modal-change-status">
    <div class="modal-dialog modal-sm">
    <div class="modal-content">
    
        <!-- Modal Header -->
        <div class="modal-header">
        <h4 class="modal-title">Change Status</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
            <select id="select-change-status" data-id="" class="select" style="width: 100%;">
                <option selected disabled>Pending</option>
                @foreach(listStatusByUserType() as $statusLabel)
                <option value="{{$statusLabel}}" class="uppercase">{{$statusLabel}}</option>
                @endforeach
            </select>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
        <button type="button" class="btn btn-info btn-save-change-status" data-dismiss="modal">Save</button>
        </div>
        
    </div>
    </div>
</div>

@section('scripts')

<script>
    const $modal = $('#modal-change-status');
    const _token = $('meta[name="csrf-token"]').attr('content');

    $('.btn-modal-change-status').on('click', function(){
        let id = $(this).data('id');

        $modal.modal('show');

        $modal.find('#select-change-status').attr('data-id', id);
    });

    $('.btn-save-change-status').on('click', function(){

        $modal.find('.btn-save-change-status').html('Sending...');

        let status = $modal.find('#select-change-status').val();
        let id     = $modal.find('#select-change-status').attr('data-id');

        let url    = '/expenses/'+id+'/status'
        console.log({status:status, '_token': _token})
        $.ajax({
            url: url,
            data: {status:status, '_token': _token},
            type: "PATCH",
            success: function (data) {
        
                location.reload();
                
            }, error: function (XMLHttpRequest, textStatus, errorThrown) {

                if (XMLHttpRequest.status == 0) {
                    alert("Check Your Network.");
                    return;
                } else if (XMLHttpRequest.status == 404) {
                    alert("Requested URL not found.");
                    return;
                } else if (XMLHttpRequest.status == 403) {
                    alert("You does not have the right permissions.");
                    return;
                } else if (XMLHttpRequest.status == 500) {
                    alert("Internel Server Error.");
                    return;
                }    

                var errors = [];
                if("errors" in XMLHttpRequest.responseJSON) {

                Object.values(XMLHttpRequest.responseJSON.errors).map(function(e){
                    if (e[0] != "" && e[0] != " ")
                        errors.push(e[0]);
                })
                } else if( "message" in XMLHttpRequest.responseJSON && "exception" in XMLHttpRequest.responseJSON ) {

                    errors.push( XMLHttpRequest.responseJSON.message );
                }
                
                alert(errors.join('<br />'));

                $modal.find('.btn-save-change-status').html('Save');
            }
        });   
    });

</script>

@endsection

resources/views/expenses/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expenses') }}
        </h2>
    </x-slot>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('expenses.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 jumbotron">

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        {{ $expense->name }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Date:</strong>
                        {{ $expense->date }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Amount:</strong>
                        {{ $expense->amount }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Status:</strong>
                        <span data-id="{{ $expense->id }}" class="@if($expense->isPending()) btn btn-link btn-modal-change-status @endif status-color-{{ $expense->status }} "
                        >
                            {{ $expense->status }}
                        </span>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Attach:</strong>
                        <a href="{{ $expense->attach }}" target="_blank" download>Download</a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Date Created:</strong>
                        {{ date_format($expense->created_at, 'jS M Y') }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('expenses.modal-change-status')

</x-app-layout>